# This is a comment
# Set a variable
@mydata = 2023-01-06
@tpprequestid = abcdefgh
@tpptransactiontid = abcdefgh
@issuer = https://bpnetsvc-ccamf-cert.bportugal.pt/
@resource= https://wwwcert.bportugal.net/apigw/conp/

@token=pmvs
# Send a GET request
#GET http://127.0.0.1:8000/api/v1/health

# Send a GET request
#GET http://127.0.0.1:8000/api/v1/token

# Send a POST request with a JSON body
POST https://plqual.ccammafra.pt:443/api/conp/cops
Content-Type: application/json
Authorization: Bearer @token

{
    "correlation_id": "abc",
    "iban": "PT50520052010010001300102",
    "timestamp": "@mydata"
}

